### ISSUE TITLE
question about your results + baselines

### ISSUE THREAD

**Issue by zozobozo** [wvangansbeke/Recurrent-Depth-Estimation#1]
Hi! great paper, started going deeper into it.
I hope it's okay i'm using this platform to ask you a question about your paper's results section.

In your table 1, you cite Wang et al.[45] as having RMSE = **5.106 [m]**; and you put them in the "supervised" section. However,  I didn't find this number in [their paper](https://arxiv.org/pdf/1904.07087.pdf); 
They actually report (in their Table 3) an RMSE "Ours-**unsupervised** / multi-view"  of **2.32 [m]**.
Is the reason for this discrepancy is a different testing split? or are you using another implementation?

I'm asking since I'm having a hard-time figuring out what's the state-of-the-art in this self-supervised multi-frame domain; I'd really appreciate your help about this!

Thanks for the help!
Z.

**Comment by vaishakhpatil** [comment]
Hi,
We contacted the authors (Wang et al.[45]) asking after the reproducibility of the results. The authors confirmed that these results (Unsupervised) are not reproducible due to a mistake in their evaluation. They provided us with their predictions (Supervised) to report their actual results in our submission. In our submission, we have cited the paper and reported the actual numbers.
Thanks,
Vaishakh

**Comment by zozobozo** [comment]
That paper did report oddly super-good results... thanks for your response, and kudos for your great work!

Thanks,
Z.

**Comment by zozobozo** [comment]
Dear Vaishakh, 
if i may trouble you for another question: do you know what is the SOTA when training with provided relative-pose data (as opposed to predicting the relative pose during training)?   
i'm having a hard time finding accuracy numbers for such methods. They are of interest, since:
  1. KITTI provides relative-pose data using its GPS/IMUs which can be [easily used](https://github.com/utiasSTARS/pykitti).
  2. no median-scaling is required, and so **real** absolute depth can be predicted and reported (just like in a supervised setup).

Again, thanks a lot for your help!
Best,
Z.
